// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"blogo/internal/db/sqlc"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockQuerier creates a new instance of MockQuerier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQuerier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQuerier {
	mock := &MockQuerier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockQuerier is an autogenerated mock type for the Querier type
type MockQuerier struct {
	mock.Mock
}

type MockQuerier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQuerier) EXPECT() *MockQuerier_Expecter {
	return &MockQuerier_Expecter{mock: &_m.Mock}
}

// CreateBlog provides a mock function for the type MockQuerier
func (_mock *MockQuerier) CreateBlog(ctx context.Context, arg sqlc.CreateBlogParams) (sqlc.Blog, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateBlog")
	}

	var r0 sqlc.Blog
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.CreateBlogParams) (sqlc.Blog, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.CreateBlogParams) sqlc.Blog); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(sqlc.Blog)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlc.CreateBlogParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_CreateBlog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBlog'
type MockQuerier_CreateBlog_Call struct {
	*mock.Call
}

// CreateBlog is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlc.CreateBlogParams
func (_e *MockQuerier_Expecter) CreateBlog(ctx interface{}, arg interface{}) *MockQuerier_CreateBlog_Call {
	return &MockQuerier_CreateBlog_Call{Call: _e.mock.On("CreateBlog", ctx, arg)}
}

func (_c *MockQuerier_CreateBlog_Call) Run(run func(ctx context.Context, arg sqlc.CreateBlogParams)) *MockQuerier_CreateBlog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.CreateBlogParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.CreateBlogParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_CreateBlog_Call) Return(blog sqlc.Blog, err error) *MockQuerier_CreateBlog_Call {
	_c.Call.Return(blog, err)
	return _c
}

func (_c *MockQuerier_CreateBlog_Call) RunAndReturn(run func(ctx context.Context, arg sqlc.CreateBlogParams) (sqlc.Blog, error)) *MockQuerier_CreateBlog_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function for the type MockQuerier
func (_mock *MockQuerier) CreateUser(ctx context.Context, arg sqlc.CreateUserParams) (sqlc.User, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 sqlc.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.CreateUserParams) (sqlc.User, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.CreateUserParams) sqlc.User); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(sqlc.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlc.CreateUserParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockQuerier_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlc.CreateUserParams
func (_e *MockQuerier_Expecter) CreateUser(ctx interface{}, arg interface{}) *MockQuerier_CreateUser_Call {
	return &MockQuerier_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, arg)}
}

func (_c *MockQuerier_CreateUser_Call) Run(run func(ctx context.Context, arg sqlc.CreateUserParams)) *MockQuerier_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.CreateUserParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.CreateUserParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_CreateUser_Call) Return(user sqlc.User, err error) *MockQuerier_CreateUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockQuerier_CreateUser_Call) RunAndReturn(run func(ctx context.Context, arg sqlc.CreateUserParams) (sqlc.User, error)) *MockQuerier_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteBlog provides a mock function for the type MockQuerier
func (_mock *MockQuerier) DeleteBlog(ctx context.Context, id int32) (int64, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBlog")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) (int64, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) int64); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_DeleteBlog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBlog'
type MockQuerier_DeleteBlog_Call struct {
	*mock.Call
}

// DeleteBlog is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *MockQuerier_Expecter) DeleteBlog(ctx interface{}, id interface{}) *MockQuerier_DeleteBlog_Call {
	return &MockQuerier_DeleteBlog_Call{Call: _e.mock.On("DeleteBlog", ctx, id)}
}

func (_c *MockQuerier_DeleteBlog_Call) Run(run func(ctx context.Context, id int32)) *MockQuerier_DeleteBlog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int32
		if args[1] != nil {
			arg1 = args[1].(int32)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_DeleteBlog_Call) Return(n int64, err error) *MockQuerier_DeleteBlog_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockQuerier_DeleteBlog_Call) RunAndReturn(run func(ctx context.Context, id int32) (int64, error)) *MockQuerier_DeleteBlog_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUser provides a mock function for the type MockQuerier
func (_mock *MockQuerier) DeleteUser(ctx context.Context, id int32) (int64, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) (int64, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) int64); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type MockQuerier_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *MockQuerier_Expecter) DeleteUser(ctx interface{}, id interface{}) *MockQuerier_DeleteUser_Call {
	return &MockQuerier_DeleteUser_Call{Call: _e.mock.On("DeleteUser", ctx, id)}
}

func (_c *MockQuerier_DeleteUser_Call) Run(run func(ctx context.Context, id int32)) *MockQuerier_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int32
		if args[1] != nil {
			arg1 = args[1].(int32)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_DeleteUser_Call) Return(n int64, err error) *MockQuerier_DeleteUser_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockQuerier_DeleteUser_Call) RunAndReturn(run func(ctx context.Context, id int32) (int64, error)) *MockQuerier_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetBlogByID provides a mock function for the type MockQuerier
func (_mock *MockQuerier) GetBlogByID(ctx context.Context, id int32) (sqlc.Blog, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetBlogByID")
	}

	var r0 sqlc.Blog
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) (sqlc.Blog, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) sqlc.Blog); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(sqlc.Blog)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_GetBlogByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBlogByID'
type MockQuerier_GetBlogByID_Call struct {
	*mock.Call
}

// GetBlogByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *MockQuerier_Expecter) GetBlogByID(ctx interface{}, id interface{}) *MockQuerier_GetBlogByID_Call {
	return &MockQuerier_GetBlogByID_Call{Call: _e.mock.On("GetBlogByID", ctx, id)}
}

func (_c *MockQuerier_GetBlogByID_Call) Run(run func(ctx context.Context, id int32)) *MockQuerier_GetBlogByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int32
		if args[1] != nil {
			arg1 = args[1].(int32)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_GetBlogByID_Call) Return(blog sqlc.Blog, err error) *MockQuerier_GetBlogByID_Call {
	_c.Call.Return(blog, err)
	return _c
}

func (_c *MockQuerier_GetBlogByID_Call) RunAndReturn(run func(ctx context.Context, id int32) (sqlc.Blog, error)) *MockQuerier_GetBlogByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByEmail provides a mock function for the type MockQuerier
func (_mock *MockQuerier) GetUserByEmail(ctx context.Context, email string) (sqlc.User, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEmail")
	}

	var r0 sqlc.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (sqlc.User, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) sqlc.User); ok {
		r0 = returnFunc(ctx, email)
	} else {
		r0 = ret.Get(0).(sqlc.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_GetUserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByEmail'
type MockQuerier_GetUserByEmail_Call struct {
	*mock.Call
}

// GetUserByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockQuerier_Expecter) GetUserByEmail(ctx interface{}, email interface{}) *MockQuerier_GetUserByEmail_Call {
	return &MockQuerier_GetUserByEmail_Call{Call: _e.mock.On("GetUserByEmail", ctx, email)}
}

func (_c *MockQuerier_GetUserByEmail_Call) Run(run func(ctx context.Context, email string)) *MockQuerier_GetUserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_GetUserByEmail_Call) Return(user sqlc.User, err error) *MockQuerier_GetUserByEmail_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockQuerier_GetUserByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (sqlc.User, error)) *MockQuerier_GetUserByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function for the type MockQuerier
func (_mock *MockQuerier) GetUserByID(ctx context.Context, id int32) (sqlc.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 sqlc.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) (sqlc.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) sqlc.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(sqlc.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type MockQuerier_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *MockQuerier_Expecter) GetUserByID(ctx interface{}, id interface{}) *MockQuerier_GetUserByID_Call {
	return &MockQuerier_GetUserByID_Call{Call: _e.mock.On("GetUserByID", ctx, id)}
}

func (_c *MockQuerier_GetUserByID_Call) Run(run func(ctx context.Context, id int32)) *MockQuerier_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int32
		if args[1] != nil {
			arg1 = args[1].(int32)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_GetUserByID_Call) Return(user sqlc.User, err error) *MockQuerier_GetUserByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockQuerier_GetUserByID_Call) RunAndReturn(run func(ctx context.Context, id int32) (sqlc.User, error)) *MockQuerier_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListBlogs provides a mock function for the type MockQuerier
func (_mock *MockQuerier) ListBlogs(ctx context.Context, arg sqlc.ListBlogsParams) ([]sqlc.Blog, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for ListBlogs")
	}

	var r0 []sqlc.Blog
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.ListBlogsParams) ([]sqlc.Blog, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.ListBlogsParams) []sqlc.Blog); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sqlc.Blog)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlc.ListBlogsParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_ListBlogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListBlogs'
type MockQuerier_ListBlogs_Call struct {
	*mock.Call
}

// ListBlogs is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlc.ListBlogsParams
func (_e *MockQuerier_Expecter) ListBlogs(ctx interface{}, arg interface{}) *MockQuerier_ListBlogs_Call {
	return &MockQuerier_ListBlogs_Call{Call: _e.mock.On("ListBlogs", ctx, arg)}
}

func (_c *MockQuerier_ListBlogs_Call) Run(run func(ctx context.Context, arg sqlc.ListBlogsParams)) *MockQuerier_ListBlogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.ListBlogsParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.ListBlogsParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_ListBlogs_Call) Return(blogs []sqlc.Blog, err error) *MockQuerier_ListBlogs_Call {
	_c.Call.Return(blogs, err)
	return _c
}

func (_c *MockQuerier_ListBlogs_Call) RunAndReturn(run func(ctx context.Context, arg sqlc.ListBlogsParams) ([]sqlc.Blog, error)) *MockQuerier_ListBlogs_Call {
	_c.Call.Return(run)
	return _c
}

// ListBlogsByUserID provides a mock function for the type MockQuerier
func (_mock *MockQuerier) ListBlogsByUserID(ctx context.Context, arg sqlc.ListBlogsByUserIDParams) ([]sqlc.Blog, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for ListBlogsByUserID")
	}

	var r0 []sqlc.Blog
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.ListBlogsByUserIDParams) ([]sqlc.Blog, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.ListBlogsByUserIDParams) []sqlc.Blog); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sqlc.Blog)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlc.ListBlogsByUserIDParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_ListBlogsByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListBlogsByUserID'
type MockQuerier_ListBlogsByUserID_Call struct {
	*mock.Call
}

// ListBlogsByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlc.ListBlogsByUserIDParams
func (_e *MockQuerier_Expecter) ListBlogsByUserID(ctx interface{}, arg interface{}) *MockQuerier_ListBlogsByUserID_Call {
	return &MockQuerier_ListBlogsByUserID_Call{Call: _e.mock.On("ListBlogsByUserID", ctx, arg)}
}

func (_c *MockQuerier_ListBlogsByUserID_Call) Run(run func(ctx context.Context, arg sqlc.ListBlogsByUserIDParams)) *MockQuerier_ListBlogsByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.ListBlogsByUserIDParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.ListBlogsByUserIDParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_ListBlogsByUserID_Call) Return(blogs []sqlc.Blog, err error) *MockQuerier_ListBlogsByUserID_Call {
	_c.Call.Return(blogs, err)
	return _c
}

func (_c *MockQuerier_ListBlogsByUserID_Call) RunAndReturn(run func(ctx context.Context, arg sqlc.ListBlogsByUserIDParams) ([]sqlc.Blog, error)) *MockQuerier_ListBlogsByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// ListUsers provides a mock function for the type MockQuerier
func (_mock *MockQuerier) ListUsers(ctx context.Context, arg sqlc.ListUsersParams) ([]sqlc.User, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for ListUsers")
	}

	var r0 []sqlc.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.ListUsersParams) ([]sqlc.User, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.ListUsersParams) []sqlc.User); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sqlc.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlc.ListUsersParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_ListUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUsers'
type MockQuerier_ListUsers_Call struct {
	*mock.Call
}

// ListUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlc.ListUsersParams
func (_e *MockQuerier_Expecter) ListUsers(ctx interface{}, arg interface{}) *MockQuerier_ListUsers_Call {
	return &MockQuerier_ListUsers_Call{Call: _e.mock.On("ListUsers", ctx, arg)}
}

func (_c *MockQuerier_ListUsers_Call) Run(run func(ctx context.Context, arg sqlc.ListUsersParams)) *MockQuerier_ListUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.ListUsersParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.ListUsersParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_ListUsers_Call) Return(users []sqlc.User, err error) *MockQuerier_ListUsers_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockQuerier_ListUsers_Call) RunAndReturn(run func(ctx context.Context, arg sqlc.ListUsersParams) ([]sqlc.User, error)) *MockQuerier_ListUsers_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateBlog provides a mock function for the type MockQuerier
func (_mock *MockQuerier) UpdateBlog(ctx context.Context, arg sqlc.UpdateBlogParams) (sqlc.Blog, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBlog")
	}

	var r0 sqlc.Blog
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.UpdateBlogParams) (sqlc.Blog, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.UpdateBlogParams) sqlc.Blog); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(sqlc.Blog)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlc.UpdateBlogParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_UpdateBlog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateBlog'
type MockQuerier_UpdateBlog_Call struct {
	*mock.Call
}

// UpdateBlog is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlc.UpdateBlogParams
func (_e *MockQuerier_Expecter) UpdateBlog(ctx interface{}, arg interface{}) *MockQuerier_UpdateBlog_Call {
	return &MockQuerier_UpdateBlog_Call{Call: _e.mock.On("UpdateBlog", ctx, arg)}
}

func (_c *MockQuerier_UpdateBlog_Call) Run(run func(ctx context.Context, arg sqlc.UpdateBlogParams)) *MockQuerier_UpdateBlog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.UpdateBlogParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.UpdateBlogParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_UpdateBlog_Call) Return(blog sqlc.Blog, err error) *MockQuerier_UpdateBlog_Call {
	_c.Call.Return(blog, err)
	return _c
}

func (_c *MockQuerier_UpdateBlog_Call) RunAndReturn(run func(ctx context.Context, arg sqlc.UpdateBlogParams) (sqlc.Blog, error)) *MockQuerier_UpdateBlog_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUser provides a mock function for the type MockQuerier
func (_mock *MockQuerier) UpdateUser(ctx context.Context, arg sqlc.UpdateUserParams) (sqlc.User, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 sqlc.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.UpdateUserParams) (sqlc.User, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.UpdateUserParams) sqlc.User); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(sqlc.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlc.UpdateUserParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type MockQuerier_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlc.UpdateUserParams
func (_e *MockQuerier_Expecter) UpdateUser(ctx interface{}, arg interface{}) *MockQuerier_UpdateUser_Call {
	return &MockQuerier_UpdateUser_Call{Call: _e.mock.On("UpdateUser", ctx, arg)}
}

func (_c *MockQuerier_UpdateUser_Call) Run(run func(ctx context.Context, arg sqlc.UpdateUserParams)) *MockQuerier_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.UpdateUserParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.UpdateUserParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_UpdateUser_Call) Return(user sqlc.User, err error) *MockQuerier_UpdateUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockQuerier_UpdateUser_Call) RunAndReturn(run func(ctx context.Context, arg sqlc.UpdateUserParams) (sqlc.User, error)) *MockQuerier_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}
